db.url=jdbc:mysql://acela.proxy.rlwy.net:14140/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
db.username=root
db.password=yrsrHXfIOrzovwTeythOAbfvsUhvibwI
data.gov.api.key=579b464db66ec23bdd000001
